// import "~/styles/globals.css";

// import { type Metadata } from "next";
// import { Geist } from "next/font/google";

// import { TRPCReactProvider } from "~/trpc/react";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

// const geist = Geist({
//   subsets: ["latin"],
//   variable: "--font-geist-sans",
// });

// export default function RootLayout({
//   children,
// }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <html lang="en" className={`${geist.variable}`}>
//       <body>
//         <TRPCReactProvider>{children}</TRPCReactProvider>
//       </body>
//     </html>
//   );
// }

/**
 * Root layout for the X Clone app.
 * Sets up:
 * - Geist font with CSS variable for Tailwind integration
 * - Custom Providers wrapper (SessionProvider + tRPC + QueryClient)
 * - Global CSS import
 * - Metadata (title "Home / X", favicon.png)
 */
import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Home / X",
  description: "",
  icons: [{ rel: "icon", url: "/favicon.png" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}